name: Update Local Repository and Run Sonar Scanner

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  pipeline:
    uses: zBrainiac/DataOpsBackbone/.github/workflows/dataops-pipeline.yml@main
    with:
      SOURCE_DATABASE: MASTER_DATA_MANAGEMENT
      SOURCE_SCHEMA: CRM_AGG_001
      DCM_PROJECT_IDENTIFIER: MASTER_DATA_MANAGEMENT.CRM_AGG_001.MDM_PROJECT
      DCM_TARGET: DEV
    secrets: inherit
